mygpoauth/login/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from . import forms


app_name = 'login'

urlpatterns = [
    path(
        '',
        auth_views.LoginView.as_view(),
        {
            'template_name': 'login/login.html',
            'authentication_form': forms.MyAuthenticationForm,
        },
        name='login',
    )
]

mygpoauth/urls.py
from django.urls import include, path
from django.contrib import admin
from django.views.generic.base import RedirectView

from mygpoauth import oauth2


urlpatterns = [
    # Examples:
    # url(r'^$', 'mygpoauth.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    path(
        '',
        RedirectView.as_view(
            url='http://mygpo-auth.rtfd.org/', permanent=False
        ),
        name='index',
    ),
    path('admin/', admin.site.urls),
    path('oauth2/', include('mygpoauth.oauth2.urls')),
    path('login/', include('mygpoauth.login.urls')),
    path('register/', include('mygpoauth.registration.urls')),
]

mygpoauth/login/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms


class MyAuthenticationForm(AuthenticationForm):

    # set attributes on the username field
    username = forms.CharField(
        label='Username',
        widget=forms.TextInput(
            attrs={'placeholder': 'Username', 'autofocus': 'autofocus'}
        ),
    )

    password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'}),
    )

mygpoauth/login/templates/login/login.html
{% extends "base.html" %}

{% block content %}

 {% if form.errors %}
  <p>Your username and password didn't match. Please try again.</p>
 {% endif %}

  <h1>
   gpodder.net
  </h1>

 <div id="login">

  <h2>Sign in</h2>

  <form method="post" action="{% url 'login:login' %}">
   {% csrf_token %}
   {{ form.username }}
   {{ form.password }}
   <button type="submit">Sign in</button>
   <input type="hidden" name="next" value="{{ next }}" />
  </form>

 </div>

{% endblock content %}